services:
  - type: web
    name: ganaplus-backend
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    branch: main
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://qlqwawawa89:Kayito2007@cluster0.njhwlri.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: SECRET_KEY
        value: gana_plus_2025_superseguro
